import { LineliffContextProvider } from "./context/lineliff.context";
import "./globals.css";
import { Sarabun } from "next/font/google";

const sarabun = Sarabun({
  weight: ["400", "500", "700"],
  subsets: ["thai"],
  variable: "--font-sara",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={sarabun.className}>
        <LineliffContextProvider>{children}</LineliffContextProvider>
      </body>
    </html>
  );
}
